#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

#
# Dockerfile for guacamole-server
#

# The Alpine Linux image that should be used as the basis for the guacd image
ARG ALPINE_BASE_IMAGE=3.18.4
FROM alpine:${ALPINE_BASE_IMAGE} AS builder
# FROM ubuntu:22.04 AS builder

# # Install build dependencies
RUN apk add --no-cache                \
        autoconf                      \
        automake                      \
        build-base                    \
        cairo-dev                     \
        cmake                         \
        cunit-dev                     \
        git                           \
        grep                          \
        libjpeg-turbo-dev             \
        libpng-dev                    \
        libtool                       \
        libwebp-dev                   \
        make                          \
        openssl1.1-compat-dev         \
        pango-dev                     \
        pulseaudio-dev                \
        util-linux-dev                \
        ffmpeg-dev \
        krb5-libs \
        krb5 \
        krb5-dev \
        krb5-server \
        libgss \
        krb5-conf \
        fuse3-dev \
        dpkg \
        wget \
        util-linux-dev

# RUN apk add --no-cache opensc

# RUN apt-get update && apt-get install -y build-essential git-core cmake libssl-dev  \
#     libcups2-dev libxml2 libxml2-dev \
#     libxrandr-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
#     libxi-dev libavutil-dev \
#     libavcodec-dev libxtst-dev libgtk-3-dev libssh-dev libpulse-dev \
#     libvte-2.91-dev libtelepathy-glib-dev libjpeg-dev \
#     libgnutls28-dev \
#     libappindicator3-dev intltool libsecret-1-dev libsystemd-dev \
#     libsoup2.4-dev libsodium-dev libjson-glib-dev libpkcs11-helper1-dev \
#     heimdal-dev
#     # libkrad0 libkrb5-3 libkrad-dev libkadm5clnt-mit12 libk5crypto3 libkrb5-3 libgssapi-krb5-2

# RUN apt-get install -y libswscale-dev libfuse3-dev libtool

# Copy source to container for sake of build
# ARG BUILD_DIR=/tmp/guacamole-server
# COPY . ${BUILD_DIR}

#
# Base directory for installed build artifacts.
#
# NOTE: Due to limitations of the Docker image build process, this value is
# duplicated in an ARG in the second stage of the build.
#
ARG PREFIX_DIR=/opt/guacamole

#
# Automatically select the latest versions of each core protocol support
# library (these can be overridden at build time if a specific version is
# needed)
#
ARG WITH_FREERDP='3(\.\d+)+'
ARG WITH_LIBSSH2='libssh2-\d+(\.\d+)+'
ARG WITH_LIBTELNET='\d+(\.\d+)+'
ARG WITH_LIBVNCCLIENT='LibVNCServer-\d+(\.\d+)+'
ARG WITH_LIBWEBSOCKETS='v\d+(\.\d+)+'

#
# Default build options for each core protocol support library, as well as
# guacamole-server itself (these can be overridden at build time if different
# options are needed)
#

ARG FREERDP_OPTS="\
    -DBUILTIN_CHANNELS=OFF \
    -DCHANNEL_URBDRC=OFF \
    -DWITH_ALSA=OFF \
    -DWITH_CAIRO=ON \
    -DWITH_CHANNELS=ON \
    -DWITH_CLIENT=ON \
    -DWITH_CUPS=OFF \
    -DWITH_DIRECTFB=OFF \
    -DWITH_FFMPEG=OFF \
    -DWITH_GSM=OFF \
    -DWITH_GSSAPI=ON \
    -DWITH_IPP=OFF \
    -DWITH_JPEG=ON \
    -DWITH_LIBSYSTEMD=OFF \
    -DWITH_MANPAGES=OFF \
    -DWITH_OPENH264=OFF \
    -DWITH_OPENSSL=ON \
    -DWITH_OSS=OFF \
    -DWITH_PCSC=OFF \
    -DWITH_PULSE=OFF \
    -DWITH_SERVER=OFF \
    -DWITH_SERVER_INTERFACE=OFF \
    -DWITH_SHADOW_MAC=OFF \
    -DWITH_SHADOW_X11=OFF \
    -DWITH_SSE2=ON \
    -DWITH_WAYLAND=OFF \
    -DWITH_X11=OFF \
    -DWITH_X264=OFF \
    -DWITH_XCURSOR=ON \
    -DWITH_XEXT=ON \
    -DWITH_XI=OFF \
    -DWITH_XINERAMA=OFF \
    -DWITH_XKBFILE=ON \
    -DWITH_XRENDER=OFF \
    -DWITH_XTEST=OFF \
    -DWITH_XV=OFF \
    -DWITH_ZLIB=ON \
    -DWITH_KRB5=ON \
    -DKRB5_TRACE=/dev/stdout \
    -DDEBUG_NLA=ON \
    -DALLOW_IN_SOURCE_BUILD=ON \
    -DWITH_OPENSC_PKCS11_LINKED=OFF \
    -DWITH_PKCS11=OFF \
    -DWITH_WINPR_DEPRECATED=ON \
    -DWITH_FREERDP_DEPRECATED_COMMANDLINE=ON \
    -DWITH_FREERDP_DEPRECATED=ON \
    -DGSS_ROOT_FLAVOUR=HEIMDAL"

ARG GUACAMOLE_SERVER_OPTS="\
    --disable-guaclog"

ARG LIBSSH2_OPTS="\
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_SHARED_LIBS=ON"

ARG LIBTELNET_OPTS="\
    --disable-static \
    --disable-util"

ARG LIBVNCCLIENT_OPTS=""

ARG LIBWEBSOCKETS_OPTS="\
    -DDISABLE_WERROR=ON \
    -DLWS_WITHOUT_SERVER=ON \
    -DLWS_WITHOUT_TESTAPPS=ON \
    -DLWS_WITHOUT_TEST_CLIENT=ON \
    -DLWS_WITHOUT_TEST_PING=ON \
    -DLWS_WITHOUT_TEST_SERVER=ON \
    -DLWS_WITHOUT_TEST_SERVER_EXTPOLL=ON \
    -DLWS_WITH_STATIC=OFF"

# Build the dependencies for guacamole-server
ARG BUILD_DIR=/tmp/guacamole-server
RUN mkdir -p ${BUILD_DIR}/src/guacd-docker/bin

COPY ./src/guacd-docker/bin/build-deps.sh ${BUILD_DIR}/src/guacd-docker/bin
RUN ${BUILD_DIR}/src/guacd-docker/bin/build-deps.sh
RUN rm -f ${BUILD_DIR}/src/guacd-docker/bin/build-deps.sh

# Copy source to container for sake of build
COPY . ${BUILD_DIR}

# Build guacamole-server and its core protocol library dependencies
RUN ${BUILD_DIR}/src/guacd-docker/bin/build-all.sh

# Record the packages of all runtime library dependencies
RUN ${BUILD_DIR}/src/guacd-docker/bin/list-dependencies.sh \
        ${PREFIX_DIR}/sbin/guacd               \
        ${PREFIX_DIR}/lib/libguac-client-*.so  \
        ${PREFIX_DIR}/lib/freerdp3/*guac*.so   \
        > ${PREFIX_DIR}/DEPENDENCIES

RUN cat ${PREFIX_DIR}/DEPENDENCIES